# ── coe 模块元数据（P3a 骨架）─────────────────────────────────────────────────
# mod_id 保持 createoreexpansion 不变（只是文件将来挪进 coe/ 目录）。
mod_id=createoreexpansion
mod_name=Create Ore Expansion
mod_version=1.0.0
mod_license=All Rights Reserved
mod_authors=hjmmd_8, Leaf
group=com.hjmmd_8.createoreexpansion
description=An expansion for create mod,add more ore block and more.
