# =============================================================================
# tools/prepare-run-published.ps1
#
# W3 test bench: prepare a "published form" game directory for the grader runs
# `publishedServer` / `publishedClient` defined in the root build.gradle.
#
# What "published form" means here
# --------------------------------
# The dev environment binds four dev mod files through neoForge.mods{} and
# -Dfml.modFolders. FML's UserdevLocator (fancymodloader 4.0.42
# net/neoforged/fml/loading/moddiscovery/locators/UserdevLocator.java) claims
# every path listed in modFolders FIRST and then scans java.class.path for
# every root that contains META-INF/neoforge.mods.toml. Anything found there
# that was not claimed becomes an additional mod file. Dropping a released jar
# into run/mods/ therefore produces fml.modloadingissue.duplicate_mod, which
# proves nothing. Instead the two `published*` runs set loadedMods to an empty
# set (no -Dfml.modFolders claim) and use an empty extra source set for the JVM
# classpath, so OUR mods can only come from <gameDir>/mods.
#
# This script is the idempotent half: wipe <gameDir>/mods, copy
#
#   1. the three released module jars (coe / cews / transmutation),
#   2. the third-party mod jars the dev runtime loads, taken from the Gradle
#      cache / the repo (list generated by the `w3ThirdPartyModJars` Gradle
#      task; NEVER downloaded here),
#   3. the extra jars already sitting in run/mods (KubeJS & friends),
#
# and write a sha256 manifest so the resulting set is reproducible.
#
# It does NOT modify any released artifact. If a released jar cannot boot as
# released, that is a finding - report it, do not patch the jar.
#
# Usage
# -----
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\prepare-run-published.ps1
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\prepare-run-published.ps1 -GameDir build/published-run-client
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\prepare-run-published.ps1 -NoThirdParty
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\prepare-run-published.ps1 -OnlyModId coe
#
# -OnlyModId <coe|cews|transmutation>[,...]
# --------------------------------
# Installs ONLY the named released module jar(s) of this mod and leaves the other
# module jars out. It filters OUR three module jars - it does NOT touch the
# third-party set (that is what -SkipModId does). Purpose = single-module
# degradation ("free combination" promise): e.g. -OnlyModId cews must still boot
# (cews declares createoreexpansion as an *optional* dependency) and, because the
# configuration is registered by :coe, must NOT create
# <gameDir>/config/createoreexpansion-common.toml.
# An unknown id is a hard failure: a typo must never silently yield an empty mods/.
#
# Exit codes: 0 ok, 1 precondition/verification failure.
# =============================================================================
[CmdletBinding()]
param(
    # Game directory to prepare. Default matches the `publishedServer` run config.
    [string]$GameDir = 'build/published-run',
    # Copy only our three module jars (isolate the mod under test).
    [switch]$NoThirdParty,
    # Third-party mod ids to leave out (isolate a suspect third-party mod).
    [string[]]$SkipModId = @(),
    # Our module jar ids to install (coe / cews / transmutation). When non-empty the
    # other module jars are left out; third-party jars are NOT affected.
    [string[]]$OnlyModId = @(),
    # Re-run the Gradle collector task even if its output file already exists.
    [switch]$RefreshThirdPartyList
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

function Fail([string]$msg) {
    Write-Host "prepare-run-published: ERROR: $msg" -ForegroundColor Red
    exit 1
}

# --- preconditions -----------------------------------------------------------
if (-not (Test-Path 'build.gradle')) { Fail "build.gradle not found; run this from the repository (root resolved to '$root')" }
if (-not (Test-Path 'coe\build.gradle')) { Fail "coe\build.gradle not found; '$root' does not look like this repository" }

# The three released module jars. This is the published set: the root jar
# (coe_integration) is the integration layer and is NOT published, and it also
# jarJar-embeds the other three - shipping both forms at once is duplicate_mod.
$moduleJars = [ordered]@{
    'coe'          = 'coe\build\libs\createoreexpansion-1.0.0.jar'
    'cews'         = 'cews\build\libs\cews-1.0.0.jar'
    'transmutation' = 'transmutation\build\libs\transmutation-1.0.0.jar'
}
foreach ($k in $moduleJars.Keys) {
    $p = $moduleJars[$k]
    if (-not (Test-Path -LiteralPath $p)) {
        Fail "missing released jar '$p'. Build it first with:  .\gradlew.bat processResources jar"
    }
}

# Normalise -OnlyModId and reject unknown ids (a typo must not be silent).
$OnlyModId = @($OnlyModId | ForEach-Object { $_.Trim().ToLowerInvariant() } | Where-Object { $_ -ne '' })
foreach ($id in $OnlyModId) {
    if (-not $moduleJars.Contains($id)) {
        Fail ("-OnlyModId '{0}' is not one of: {1}" -f $id, (($moduleJars.Keys) -join ', '))
    }
}

# Warn (do not fail) when a module jar looks older than that module's sources.
foreach ($k in $moduleJars.Keys) {
    $jar = Get-Item $moduleJars[$k]
    $srcRoot = Join-Path $k 'src'
    if (Test-Path $srcRoot) {
        $newest = Get-ChildItem $srcRoot -Recurse -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if ($newest -and $newest.LastWriteTime -gt $jar.LastWriteTime) {
            Write-Host ("prepare-run-published: WARNING: {0} is older than {1} - rebuild with .\gradlew.bat processResources jar" -f $jar.Name, $newest.FullName) -ForegroundColor Yellow
        }
    }
}

# --- third-party jar list ----------------------------------------------------
$listFile = 'build\patch\w3-third-party-mod-jars.txt'
if ($NoThirdParty) {
    Write-Host 'prepare-run-published: -NoThirdParty: copying only the three module jars'
} elseif ((-not (Test-Path $listFile)) -or $RefreshThirdPartyList) {
    Write-Host "prepare-run-published: generating $listFile (offline Gradle task w3ThirdPartyModJars)"
    & cmd /c ".\gradlew.bat --offline -q w3ThirdPartyModJars" | Out-Null
    if (-not (Test-Path $listFile)) { Fail "Gradle task w3ThirdPartyModJars did not produce $listFile" }
}

# --- build the copy plan (name -> source), detecting name collisions ---------
$plan = @{}          # file name -> full source path
$planOwner = @{}     # file name -> provenance label

function Add-Planned([string]$name, [string]$src, [string]$origin) {
    # -LiteralPath everywhere: some jars in run/mods are named "[Ponderer] ...",
    # and PowerShell's default path cmdlets treat [ ] as wildcards.
    if (-not (Test-Path -LiteralPath $src)) {
        Write-Host ("prepare-run-published: WARNING: listed jar not present, skipping: {0} ({1})" -f $src, $origin) -ForegroundColor Yellow
        return
    }
    $full = (Resolve-Path -LiteralPath $src).Path
    if ($plan.ContainsKey($name)) {
        if ($plan[$name] -ne $full) {
            Fail ("two different sources want the same file name '{0}':`n    {1}  [{2}]`n    {3}  [{4}]" -f $name, $plan[$name], $planOwner[$name], $full, $origin)
        }
        return
    }
    $plan[$name] = $full
    $planOwner[$name] = $origin
}

# 1. our three released module jars (or, with -OnlyModId, just the named subset)
foreach ($k in $moduleJars.Keys) {
    if ($OnlyModId.Count -gt 0 -and -not ($OnlyModId -contains $k)) {
        Write-Host "prepare-run-published: -OnlyModId: leaving out module jar '$k'"
        continue
    }
    $p = $moduleJars[$k]
    Add-Planned (Split-Path -Leaf $p) $p "module:$k"
}

if (-not $NoThirdParty) {
    # 2. third-party mod jars the dev runtime loads (Gradle cache / repo, no downloads)
    if (Test-Path $listFile) {
        foreach ($line in (Get-Content $listFile)) {
            $t = $line.Trim()
            if ($t -eq '' -or $t.StartsWith('#')) { continue }
            $parts = $t -split "`t", 2
            $src = $parts[0]
            $modId = if ($parts.Count -gt 1) { $parts[1] } else { '?' }
            if ($SkipModId -contains $modId) {
                Write-Host "prepare-run-published: -SkipModId: leaving out $modId ($src)"
                continue
            }
            Add-Planned (Split-Path -Leaf $src) $src "thirdparty:$modId"
        }
    }
    # 3. extra jars already present in run/mods (KubeJS, PonderJS, Ponderer, Rhino, ...)
    if (Test-Path 'run\mods') {
        Get-ChildItem 'run\mods' -File -Filter *.jar | ForEach-Object {
            Add-Planned $_.Name $_.FullName 'rundev:run/mods'
        }
    }
}

# --- materialise the game dir ------------------------------------------------
$modsDir = Join-Path $GameDir 'mods'
if (Test-Path $modsDir) {
    Remove-Item $modsDir -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $modsDir | Out-Null

$manifest = New-Object System.Collections.Generic.List[string]
$manifest.Add("# W3 published-form mod set")
$manifest.Add("# gameDir  : $GameDir")
if ($OnlyModId.Count -gt 0) { $manifest.Add("# onlyMod  : $($OnlyModId -join ',')") }
$manifest.Add("# prepared : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$manifest.Add("# name`tsha256`tbytes`torigin`tsource")

foreach ($name in ($plan.Keys | Sort-Object)) {
    $src = $plan[$name]
    Copy-Item -LiteralPath $src -Destination (Join-Path $modsDir $name) -Force
    $h = Get-FileHash -LiteralPath $src -Algorithm SHA256
    $len = (Get-Item -LiteralPath $src).Length
    $manifest.Add(("{0}`t{1}`t{2}`t{3}`t{4}" -f $name, $h.Hash, $len, $planOwner[$name], $src))
}

$manifestPath = Join-Path $GameDir 'mods-manifest.txt'
New-Item -ItemType Directory -Force -Path $GameDir | Out-Null
[System.IO.File]::WriteAllLines((Join-Path (Get-Location) $manifestPath), $manifest, (New-Object System.Text.UTF8Encoding($false)))

# A fresh game directory has no eula.txt and the dedicated server refuses to
# start without it. Write it here so the bench is a single command.
$eulaPath = Join-Path $GameDir 'eula.txt'
if (-not (Test-Path -LiteralPath $eulaPath)) {
    [System.IO.File]::WriteAllText((Join-Path (Get-Location) $eulaPath), "#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).`neula=true`n", (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "prepare-run-published: wrote $eulaPath (eula=true)"
}

# server.properties with RCON enabled: the only reliable way to stop the
# dedicated server gracefully from a non-interactive session (Gradle's JavaExec
# stdin plumbing is not guaranteed). Purely additive; overwritten never.
$propsPath = Join-Path $GameDir 'server.properties'
if (-not (Test-Path -LiteralPath $propsPath)) {
    $props = @(
        'enable-rcon=true',
        'rcon.port=25585',
        'rcon.password=w3bench',
        'online-mode=true',
        'level-seed=w3published',
        'max-tick-time=-1',
        'sync-chunk-writes=false'
    ) -join "`n"
    [System.IO.File]::WriteAllText((Join-Path (Get-Location) $propsPath), $props + "`n", (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "prepare-run-published: wrote $propsPath (rcon on 127.0.0.1:25585)"
}

Write-Host ("prepare-run-published: OK  {0} jar(s) installed into {1}" -f $plan.Count, $modsDir) -ForegroundColor Green
foreach ($name in ($plan.Keys | Sort-Object)) {
    Write-Host ("    {0,-52} <- {1}" -f $name, $planOwner[$name])
}
Write-Host "prepare-run-published: manifest -> $manifestPath"
exit 0
